2022-07-03 18:14:06,356 -  nornir.core -     INFO -        run() - Running task 'host_parm' with args {} on 4 hosts
2022-07-05 14:18:50,439 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 14:18:50,445 - nornir.core.task -    ERROR -      start() - Host 'sw1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 321, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
aruba_os
aruba_osswitch
aruba_procurve
avaya_ers
avaya_vsp
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s300
cisco_tp
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
coriant
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dlink_ds
eltex
eltex_esr
endace
enterasys
ericsson_ipos
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
flexvnf
fortinet
generic
generic_termserver
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_vrpv8
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
linux
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
netapp_cdot
netgear_prosafe
netscaler
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
sixwind_os
sophos_sfos
supermicro_smis
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros

2022-07-05 14:18:50,446 - nornir.core.task -    ERROR -      start() - Host 'sw3': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 321, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
aruba_os
aruba_osswitch
aruba_procurve
avaya_ers
avaya_vsp
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s300
cisco_tp
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
coriant
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dlink_ds
eltex
eltex_esr
endace
enterasys
ericsson_ipos
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
flexvnf
fortinet
generic
generic_termserver
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_vrpv8
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
linux
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
netapp_cdot
netgear_prosafe
netscaler
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
sixwind_os
sophos_sfos
supermicro_smis
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros

2022-07-05 14:18:50,446 - nornir.core.task -    ERROR -      start() - Host 'sw2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 321, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
aruba_os
aruba_osswitch
aruba_procurve
avaya_ers
avaya_vsp
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s300
cisco_tp
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
coriant
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dlink_ds
eltex
eltex_esr
endace
enterasys
ericsson_ipos
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
flexvnf
fortinet
generic
generic_termserver
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_vrpv8
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
linux
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
netapp_cdot
netgear_prosafe
netscaler
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
sixwind_os
sophos_sfos
supermicro_smis
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros

2022-07-05 14:18:50,446 - nornir.core.task -    ERROR -      start() - Host 'sw4': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 321, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
aruba_os
aruba_osswitch
aruba_procurve
avaya_ers
avaya_vsp
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s300
cisco_tp
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
coriant
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dlink_ds
eltex
eltex_esr
endace
enterasys
ericsson_ipos
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
flexvnf
fortinet
generic
generic_termserver
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_vrpv8
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
linux
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
netapp_cdot
netgear_prosafe
netscaler
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
sixwind_os
sophos_sfos
supermicro_smis
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros

2022-07-05 14:19:15,529 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 14:31:09,367 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 14:31:18,143 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:31:27,655 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:31:37,148 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:31:46,635 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:31:56,149 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:32:05,658 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:32:15,205 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:32:24,710 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:32:34,232 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:32:43,740 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:32:53,246 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:33:02,753 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:33:12,293 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display interface description | inc Nornir'} on 4 hosts
2022-07-05 14:34:43,416 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 14:38:58,151 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 14:41:41,304 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:42:12,879 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:42:37,264 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:42:56,924 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:43:37,023 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 14:43:45,897 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:43:55,391 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:44:04,902 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:44:14,400 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:44:23,921 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:44:33,426 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:44:42,924 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:44:52,425 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:45:01,965 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:45:11,473 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:45:20,978 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:45:30,494 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:45:40,007 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display interface description | inc Nornir'} on 4 hosts
2022-07-05 14:46:10,527 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 14:46:19,530 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:46:29,035 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:46:38,550 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:46:48,088 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:46:57,593 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:47:07,101 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:47:16,612 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:47:26,148 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:47:35,630 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:47:45,139 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/1', 'description Access Port to VLAN 1 (Nornir)']} on 4 hosts
2022-07-05 14:47:54,654 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/2', 'description Trunk Port (Nornir)']} on 4 hosts
2022-07-05 14:48:04,137 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['interface GigabitEthernet0/0/3', 'description Access Port to VLAN 999 (Nornir)']} on 4 hosts
2022-07-05 14:48:13,633 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display interface description | inc Nornir'} on 4 hosts
2022-07-05 14:54:10,352 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 16:38:51,882 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'display current-configuration | be interface GigabitEthernet', 'use_textfsm': True} on 4 hosts
2022-07-05 16:38:56,916 - nornir.core.task -    ERROR -      start() - Host 'sw4': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\util.py", line 279, in retry_on_signal
    return function()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: huawei 192.168.59.40:22



2022-07-05 16:38:56,917 - nornir.core.task -    ERROR -      start() - Host 'sw2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\util.py", line 279, in retry_on_signal
    return function()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: huawei 192.168.59.20:22



2022-07-05 16:38:56,917 - nornir.core.task -    ERROR -      start() - Host 'sw1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\util.py", line 279, in retry_on_signal
    return function()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: huawei 192.168.59.10:22



2022-07-05 16:38:56,917 - nornir.core.task -    ERROR -      start() - Host 'sw3': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 935, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\util.py", line 279, in retry_on_signal
    return function()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\paramiko\client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\nornir_netmiko\connections\netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\29756\PycharmProjects\network_lab\venv\lib\site-packages\netmiko\base_connection.py", line 957, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: huawei 192.168.59.30:22



